export enum ImpactLevel {
    LOW = 1,
    MEDIUM = 2,
    HIGH = 3,
    CRITICAL = 4,
}

export const INSTITUTIONAL_MAP: Record<string, ImpactLevel> = {
    // ═══════════════════════════════════════════════
    //  CENTRAL BANKS — CRITICAL / HIGH
    // ═══════════════════════════════════════════════
    'federal reserve': ImpactLevel.CRITICAL,
    fed: ImpactLevel.CRITICAL,
    fomc: ImpactLevel.CRITICAL,
    powell: ImpactLevel.CRITICAL,
    'jerome powell': ImpactLevel.CRITICAL,
    'fed chair': ImpactLevel.CRITICAL,
    'fed minutes': ImpactLevel.CRITICAL,
    'fed pivot': ImpactLevel.CRITICAL,
    'fed hike': ImpactLevel.CRITICAL,
    'fed cut': ImpactLevel.CRITICAL,
    'rate decision': ImpactLevel.CRITICAL,
    'rate hike': ImpactLevel.CRITICAL,
    'rate cut': ImpactLevel.CRITICAL,
    'interest rates': ImpactLevel.CRITICAL,
    'federal funds rate': ImpactLevel.CRITICAL,
    'emergency rate cut': ImpactLevel.CRITICAL,
    'quantitative easing': ImpactLevel.CRITICAL,
    'quantitative tightening': ImpactLevel.CRITICAL,
    qe: ImpactLevel.CRITICAL,
    qt: ImpactLevel.CRITICAL,
    'balance sheet': ImpactLevel.HIGH,
    'reverse repo': ImpactLevel.MEDIUM,
    'bank of japan': ImpactLevel.CRITICAL,
    boj: ImpactLevel.CRITICAL,
    ueda: ImpactLevel.HIGH,
    kuroda: ImpactLevel.HIGH,
    'yield curve control': ImpactLevel.CRITICAL,
    ycc: ImpactLevel.CRITICAL,
    ecb: ImpactLevel.CRITICAL,
    'european central bank': ImpactLevel.CRITICAL,
    lagarde: ImpactLevel.CRITICAL,
    'christine lagarde': ImpactLevel.CRITICAL,
    bce: ImpactLevel.HIGH,
    'bank of england': ImpactLevel.HIGH,
    boe: ImpactLevel.HIGH,
    'andrew bailey': ImpactLevel.HIGH,
    'bank of canada': ImpactLevel.HIGH,
    boc: ImpactLevel.HIGH,
    'tiff macklem': ImpactLevel.MEDIUM,
    'reserve bank of australia': ImpactLevel.HIGH,
    rba: ImpactLevel.HIGH,
    'peoples bank of china': ImpactLevel.CRITICAL,
    pboc: ImpactLevel.CRITICAL,
    'swiss national bank': ImpactLevel.HIGH,
    snb: ImpactLevel.HIGH,
    'reserve bank of india': ImpactLevel.MEDIUM,
    rbi: ImpactLevel.MEDIUM,
    'banco de mexico': ImpactLevel.LOW,
    banxico: ImpactLevel.LOW,
    'central bank': ImpactLevel.HIGH,
    'monetary policy': ImpactLevel.CRITICAL,
    dovish: ImpactLevel.HIGH,
    hawkish: ImpactLevel.HIGH,
    'neutral stance': ImpactLevel.MEDIUM,
    'terminal rate': ImpactLevel.HIGH,
    'dot plot': ImpactLevel.HIGH,
    'forward guidance': ImpactLevel.HIGH,
    'policy statement': ImpactLevel.HIGH,

    // ═══════════════════════════════════════════════
    //  ECONOMIC INDICATORS — HIGH / CRITICAL
    // ═══════════════════════════════════════════════
    cpi: ImpactLevel.CRITICAL,
    'consumer price index': ImpactLevel.CRITICAL,
    'core cpi': ImpactLevel.CRITICAL,
    pce: ImpactLevel.CRITICAL,
    'core pce': ImpactLevel.CRITICAL,
    'personal consumption expenditure': ImpactLevel.HIGH,
    nfp: ImpactLevel.CRITICAL,
    'non-farm payrolls': ImpactLevel.CRITICAL,
    'jobs report': ImpactLevel.CRITICAL,
    'unemployment rate': ImpactLevel.HIGH,
    'jobless claims': ImpactLevel.HIGH,
    'initial jobless claims': ImpactLevel.HIGH,
    'continuing claims': ImpactLevel.MEDIUM,
    gdp: ImpactLevel.CRITICAL,
    'gross domestic product': ImpactLevel.CRITICAL,
    'gdp growth': ImpactLevel.HIGH,
    'gdp revision': ImpactLevel.HIGH,
    ppi: ImpactLevel.HIGH,
    'producer price index': ImpactLevel.HIGH,
    ism: ImpactLevel.HIGH,
    'manufacturing pmi': ImpactLevel.HIGH,
    'services pmi': ImpactLevel.HIGH,
    'composite pmi': ImpactLevel.HIGH,
    pmi: ImpactLevel.HIGH,
    'retail sales': ImpactLevel.HIGH,
    'durable goods': ImpactLevel.HIGH,
    'trade balance': ImpactLevel.MEDIUM,
    'current account': ImpactLevel.MEDIUM,
    'housing starts': ImpactLevel.MEDIUM,
    'building permits': ImpactLevel.MEDIUM,
    'existing home sales': ImpactLevel.MEDIUM,
    'new home sales': ImpactLevel.MEDIUM,
    'consumer confidence': ImpactLevel.HIGH,
    'michigan sentiment': ImpactLevel.HIGH,
    'university of michigan': ImpactLevel.HIGH,
    'conference board': ImpactLevel.HIGH,
    'inflation expectations': ImpactLevel.HIGH,
    'breakeven inflation': ImpactLevel.HIGH,
    tips: ImpactLevel.HIGH,
    'real yields': ImpactLevel.HIGH,
    'wage growth': ImpactLevel.HIGH,
    'average hourly earnings': ImpactLevel.HIGH,
    'labor participation rate': ImpactLevel.MEDIUM,
    jolts: ImpactLevel.MEDIUM,
    'job openings': ImpactLevel.MEDIUM,
    'ism services': ImpactLevel.HIGH,
    'empire state': ImpactLevel.MEDIUM,
    'philly fed': ImpactLevel.MEDIUM,
    'beige book': ImpactLevel.MEDIUM,
    'industrial production': ImpactLevel.MEDIUM,
    'capacity utilization': ImpactLevel.MEDIUM,
    'factory orders': ImpactLevel.MEDIUM,
    'wholesale inventories': ImpactLevel.LOW,
    'import prices': ImpactLevel.MEDIUM,
    'export prices': ImpactLevel.MEDIUM,

    // ═══════════════════════════════════════════════
    //  US GOVERNMENT / FISCAL / TREASURY
    // ═══════════════════════════════════════════════
    'us treasury': ImpactLevel.CRITICAL,
    'janet yellen': ImpactLevel.HIGH,
    yellen: ImpactLevel.HIGH,
    'treasury secretary': ImpactLevel.HIGH,
    'debt ceiling': ImpactLevel.CRITICAL,
    'government shutdown': ImpactLevel.HIGH,
    'fiscal cliff': ImpactLevel.HIGH,
    'budget deficit': ImpactLevel.HIGH,
    'national debt': ImpactLevel.HIGH,
    'treasury auction': ImpactLevel.HIGH,
    'treasury yield': ImpactLevel.CRITICAL,
    '10-year yield': ImpactLevel.CRITICAL,
    '2-year yield': ImpactLevel.HIGH,
    '30-year yield': ImpactLevel.HIGH,
    'yield curve': ImpactLevel.CRITICAL,
    'yield curve inversion': ImpactLevel.CRITICAL,
    'inverted yield curve': ImpactLevel.CRITICAL,
    'term premium': ImpactLevel.HIGH,
    'treasury issuance': ImpactLevel.HIGH,
    'bid-to-cover': ImpactLevel.MEDIUM,
    irs: ImpactLevel.LOW,
    'tax policy': ImpactLevel.HIGH,
    'tax cut': ImpactLevel.HIGH,
    'tax hike': ImpactLevel.HIGH,
    'bipartisan deal': ImpactLevel.MEDIUM,
    congress: ImpactLevel.HIGH,
    senate: ImpactLevel.MEDIUM,
    'white house': ImpactLevel.HIGH,
    biden: ImpactLevel.HIGH,
    trump: ImpactLevel.CRITICAL,
    'executive order': ImpactLevel.HIGH,
    'stimulus package': ImpactLevel.HIGH,
    'fiscal stimulus': ImpactLevel.HIGH,
    'infrastructure bill': ImpactLevel.MEDIUM,
    'spending bill': ImpactLevel.MEDIUM,
    sanctions: ImpactLevel.HIGH,
    tariffs: ImpactLevel.HIGH,
    'trade war': ImpactLevel.HIGH,
    'trade deal': ImpactLevel.HIGH,
    "moody's": ImpactLevel.HIGH,
    fitch: ImpactLevel.HIGH,
    's&p': ImpactLevel.HIGH,
    'credit rating': ImpactLevel.HIGH,
    downgrade: ImpactLevel.CRITICAL,
    'credit watch': ImpactLevel.HIGH,

    // ═══════════════════════════════════════════════
    //  REGULATORS — CRYPTO & FINANCIAL
    // ═══════════════════════════════════════════════
    sec: ImpactLevel.CRITICAL,
    'securities and exchange commission': ImpactLevel.CRITICAL,
    'gary gensler': ImpactLevel.CRITICAL,
    gensler: ImpactLevel.HIGH,
    cftc: ImpactLevel.HIGH,
    'commodity futures trading commission': ImpactLevel.HIGH,
    'financial stability board': ImpactLevel.HIGH,
    fsb: ImpactLevel.HIGH,
    occ: ImpactLevel.MEDIUM,
    fdic: ImpactLevel.HIGH,
    'office of the comptroller': ImpactLevel.MEDIUM,
    finra: ImpactLevel.MEDIUM,
    fca: ImpactLevel.HIGH,
    'financial conduct authority': ImpactLevel.HIGH,
    bafin: ImpactLevel.MEDIUM,
    mas: ImpactLevel.MEDIUM,
    'monetary authority of singapore': ImpactLevel.MEDIUM,
    mica: ImpactLevel.HIGH,
    'crypto regulation': ImpactLevel.CRITICAL,
    'crypto ban': ImpactLevel.CRITICAL,
    'crypto crackdown': ImpactLevel.HIGH,
    doj: ImpactLevel.HIGH,
    'department of justice': ImpactLevel.HIGH,
    'wells fargo agreement': ImpactLevel.LOW,
    ofac: ImpactLevel.HIGH,
    'anti-money laundering': ImpactLevel.HIGH,
    aml: ImpactLevel.HIGH,
    kyc: ImpactLevel.MEDIUM,
    'bank secrecy act': ImpactLevel.MEDIUM,
    fatf: ImpactLevel.HIGH,
    'financial action task force': ImpactLevel.HIGH,

    // ═══════════════════════════════════════════════
    //  CRYPTO — EXCHANGES / PROTOCOLS / EVENTS
    // ═══════════════════════════════════════════════
    binance: ImpactLevel.CRITICAL,
    cz: ImpactLevel.HIGH,
    'changpeng zhao': ImpactLevel.HIGH,
    coinbase: ImpactLevel.HIGH,
    kraken: ImpactLevel.MEDIUM,
    ftx: ImpactLevel.CRITICAL,
    'sam bankman-fried': ImpactLevel.HIGH,
    sbf: ImpactLevel.HIGH,
    bybit: ImpactLevel.MEDIUM,
    okx: ImpactLevel.MEDIUM,
    gemini: ImpactLevel.MEDIUM,
    bitstamp: ImpactLevel.LOW,
    bitfinex: ImpactLevel.MEDIUM,
    huobi: ImpactLevel.MEDIUM,
    kucoin: ImpactLevel.MEDIUM,
    'crypto.com': ImpactLevel.MEDIUM,
    uniswap: ImpactLevel.MEDIUM,
    aave: ImpactLevel.MEDIUM,
    curve: ImpactLevel.MEDIUM,
    maker: ImpactLevel.MEDIUM,
    makerdao: ImpactLevel.MEDIUM,
    compound: ImpactLevel.LOW,
    chainlink: ImpactLevel.MEDIUM,
    solana: ImpactLevel.HIGH,
    avalanche: ImpactLevel.MEDIUM,
    polygon: ImpactLevel.MEDIUM,
    arbitrum: ImpactLevel.MEDIUM,
    optimism: ImpactLevel.MEDIUM,
    'layer 2': ImpactLevel.MEDIUM,
    'layer-2': ImpactLevel.MEDIUM,
    lightning: ImpactLevel.MEDIUM,
    'lightning network': ImpactLevel.MEDIUM,
    bitcoin: ImpactLevel.CRITICAL,
    btc: ImpactLevel.CRITICAL,
    ethereum: ImpactLevel.CRITICAL,
    eth: ImpactLevel.CRITICAL,
    halving: ImpactLevel.CRITICAL,
    'bitcoin halving': ImpactLevel.CRITICAL,
    'mining difficulty': ImpactLevel.MEDIUM,
    'hash rate': ImpactLevel.MEDIUM,
    'miner capitulation': ImpactLevel.HIGH,
    'miner revenue': ImpactLevel.MEDIUM,
    stablecoin: ImpactLevel.HIGH,
    usdt: ImpactLevel.HIGH,
    tether: ImpactLevel.HIGH,
    usdc: ImpactLevel.HIGH,
    circle: ImpactLevel.HIGH,
    busd: ImpactLevel.MEDIUM,
    dai: ImpactLevel.MEDIUM,
    depeg: ImpactLevel.CRITICAL,
    'flash crash': ImpactLevel.HIGH,
    liquidation: ImpactLevel.HIGH,
    'long liquidation': ImpactLevel.HIGH,
    'short squeeze': ImpactLevel.HIGH,
    'funding rate': ImpactLevel.MEDIUM,
    'open interest': ImpactLevel.MEDIUM,
    'spot etf': ImpactLevel.CRITICAL,
    'bitcoin etf': ImpactLevel.CRITICAL,
    'ethereum etf': ImpactLevel.HIGH,
    etf: ImpactLevel.HIGH,
    grayscale: ImpactLevel.HIGH,
    gbtc: ImpactLevel.HIGH,
    microstrategy: ImpactLevel.HIGH,
    'michael saylor': ImpactLevel.MEDIUM,
    defi: ImpactLevel.MEDIUM,
    nft: ImpactLevel.MEDIUM,
    'rug pull': ImpactLevel.HIGH,
    'smart contract': ImpactLevel.MEDIUM,
    exploit: ImpactLevel.HIGH,
    hack: ImpactLevel.HIGH,
    'exchange hack': ImpactLevel.CRITICAL,
    'protocol exploit': ImpactLevel.HIGH,
    'bridge hack': ImpactLevel.HIGH,
    'wallet drainer': ImpactLevel.MEDIUM,
    'fear and greed index': ImpactLevel.MEDIUM,
    'fear & greed': ImpactLevel.MEDIUM,
    'crypto winter': ImpactLevel.HIGH,
    'bull run': ImpactLevel.HIGH,
    'altcoin season': ImpactLevel.MEDIUM,
    'bitcoin dominance': ImpactLevel.MEDIUM,

    // ═══════════════════════════════════════════════
    //  INSTITUTIONAL INVESTORS / ASSET MANAGERS
    // ═══════════════════════════════════════════════
    blackrock: ImpactLevel.CRITICAL,
    'larry fink': ImpactLevel.HIGH,
    vanguard: ImpactLevel.HIGH,
    'state street': ImpactLevel.HIGH,
    fidelity: ImpactLevel.HIGH,
    pimco: ImpactLevel.HIGH,
    bridgewater: ImpactLevel.HIGH,
    'ray dalio': ImpactLevel.HIGH,
    citadel: ImpactLevel.HIGH,
    'ken griffin': ImpactLevel.MEDIUM,
    'two sigma': ImpactLevel.MEDIUM,
    'renaissance technologies': ImpactLevel.MEDIUM,
    aqr: ImpactLevel.MEDIUM,
    'man group': ImpactLevel.MEDIUM,
    'millennium management': ImpactLevel.MEDIUM,
    point72: ImpactLevel.MEDIUM,
    'tiger global': ImpactLevel.MEDIUM,
    softbank: ImpactLevel.HIGH,
    'masayoshi son': ImpactLevel.MEDIUM,
    'sovereign wealth fund': ImpactLevel.HIGH,
    'pension fund': ImpactLevel.HIGH,
    'endowment fund': ImpactLevel.MEDIUM,
    'hedge fund': ImpactLevel.HIGH,
    'mutual fund': ImpactLevel.MEDIUM,
    'passive fund': ImpactLevel.MEDIUM,
    'index fund': ImpactLevel.MEDIUM,
    'etf flows': ImpactLevel.HIGH,
    'institutional flows': ImpactLevel.HIGH,
    whale: ImpactLevel.HIGH,
    'smart money': ImpactLevel.MEDIUM,
    'cot report': ImpactLevel.MEDIUM,
    'commitment of traders': ImpactLevel.MEDIUM,
    'cftc positioning': ImpactLevel.MEDIUM,
    'speculative positioning': ImpactLevel.MEDIUM,
    'net long': ImpactLevel.MEDIUM,
    'net short': ImpactLevel.MEDIUM,
    'short interest': ImpactLevel.MEDIUM,
    'short covering': ImpactLevel.HIGH,

    // ═══════════════════════════════════════════════
    //  MAJOR BANKS / BROKER DEALERS
    // ═══════════════════════════════════════════════
    'goldman sachs': ImpactLevel.HIGH,
    gs: ImpactLevel.HIGH,
    jpmorgan: ImpactLevel.HIGH,
    'jp morgan': ImpactLevel.HIGH,
    'jamie dimon': ImpactLevel.HIGH,
    'morgan stanley': ImpactLevel.HIGH,
    'bank of america': ImpactLevel.HIGH,
    bofa: ImpactLevel.HIGH,
    citigroup: ImpactLevel.HIGH,
    citi: ImpactLevel.HIGH,
    'wells fargo': ImpactLevel.MEDIUM,
    barclays: ImpactLevel.MEDIUM,
    'deutsche bank': ImpactLevel.HIGH,
    ubs: ImpactLevel.HIGH,
    'credit suisse': ImpactLevel.HIGH,
    'societe generale': ImpactLevel.MEDIUM,
    'bnp paribas': ImpactLevel.MEDIUM,
    hsbc: ImpactLevel.MEDIUM,
    'standard chartered': ImpactLevel.MEDIUM,
    nomura: ImpactLevel.MEDIUM,
    'bank stress test': ImpactLevel.HIGH,
    'bank failure': ImpactLevel.CRITICAL,
    'bank run': ImpactLevel.CRITICAL,
    'silicon valley bank': ImpactLevel.HIGH,
    svb: ImpactLevel.HIGH,
    'signature bank': ImpactLevel.HIGH,
    'first republic': ImpactLevel.HIGH,
    'regional bank': ImpactLevel.HIGH,
    'banking crisis': ImpactLevel.CRITICAL,
    'bank bailout': ImpactLevel.CRITICAL,
    'fdic seizure': ImpactLevel.CRITICAL,
    'systemic risk': ImpactLevel.CRITICAL,
    'too big to fail': ImpactLevel.HIGH,
    'repo market': ImpactLevel.HIGH,
    'overnight repo': ImpactLevel.MEDIUM,

    // ═══════════════════════════════════════════════
    //  GOLD / PRECIOUS METALS SPECIFIC
    // ═══════════════════════════════════════════════
    'world gold council': ImpactLevel.HIGH,
    wgc: ImpactLevel.HIGH,
    comex: ImpactLevel.HIGH,
    'gold futures': ImpactLevel.HIGH,
    'gold etf': ImpactLevel.HIGH,
    gld: ImpactLevel.HIGH,
    iau: ImpactLevel.MEDIUM,
    'central bank gold': ImpactLevel.HIGH,
    'gold reserves': ImpactLevel.HIGH,
    'fort knox': ImpactLevel.MEDIUM,
    'gold repatriation': ImpactLevel.MEDIUM,
    'gold lease rate': ImpactLevel.MEDIUM,
    'gold carry trade': ImpactLevel.MEDIUM,
    'gold-to-silver ratio': ImpactLevel.MEDIUM,
    'gold silver ratio': ImpactLevel.MEDIUM,
    'xau/usd': ImpactLevel.HIGH,
    xauusd: ImpactLevel.HIGH,
    'xag/usd': ImpactLevel.MEDIUM,
    xagusd: ImpactLevel.MEDIUM,
    lbma: ImpactLevel.HIGH,
    'london bullion market': ImpactLevel.HIGH,
    'gold fix': ImpactLevel.MEDIUM,
    'de-dollarization': ImpactLevel.HIGH,
    dedollarization: ImpactLevel.HIGH,
    'brics gold': ImpactLevel.HIGH,
    'gold backed': ImpactLevel.HIGH,
    'safe haven': ImpactLevel.HIGH,
    'safe-haven': ImpactLevel.HIGH,
    newmont: ImpactLevel.MEDIUM,
    barrick: ImpactLevel.MEDIUM,
    'agnico eagle': ImpactLevel.LOW,
    kinross: ImpactLevel.LOW,
    'gold miner': ImpactLevel.MEDIUM,
    'mining strike': ImpactLevel.MEDIUM,
    gdx: ImpactLevel.MEDIUM,
    gdxj: ImpactLevel.LOW,

    // ═══════════════════════════════════════════════
    //  OIL / ENERGY
    // ═══════════════════════════════════════════════
    opec: ImpactLevel.CRITICAL,
    'opec+': ImpactLevel.CRITICAL,
    'saudi arabia': ImpactLevel.CRITICAL,
    aramco: ImpactLevel.HIGH,
    'saudi aramco': ImpactLevel.HIGH,
    mbs: ImpactLevel.HIGH,
    'prince salman': ImpactLevel.HIGH,
    'russia oil': ImpactLevel.CRITICAL,
    eia: ImpactLevel.HIGH,
    'energy information administration': ImpactLevel.HIGH,
    'crude inventory': ImpactLevel.HIGH,
    'oil inventory': ImpactLevel.HIGH,
    cushing: ImpactLevel.HIGH,
    'oil production cut': ImpactLevel.CRITICAL,
    'barrel per day': ImpactLevel.HIGH,
    wti: ImpactLevel.HIGH,
    'brent crude': ImpactLevel.HIGH,
    brent: ImpactLevel.HIGH,
    'wti crude': ImpactLevel.HIGH,
    'oil prices': ImpactLevel.HIGH,
    'crude oil': ImpactLevel.HIGH,
    'natural gas': ImpactLevel.HIGH,
    lng: ImpactLevel.HIGH,
    'liquefied natural gas': ImpactLevel.HIGH,
    'energy crisis': ImpactLevel.HIGH,
    pipeline: ImpactLevel.MEDIUM,
    'nord stream': ImpactLevel.HIGH,
    'strategic petroleum reserve': ImpactLevel.HIGH,
    spr: ImpactLevel.HIGH,
    'oil demand': ImpactLevel.HIGH,
    'oil supply': ImpactLevel.HIGH,
    'rig count': ImpactLevel.MEDIUM,
    'baker hughes': ImpactLevel.MEDIUM,
    shale: ImpactLevel.HIGH,
    'permian basin': ImpactLevel.MEDIUM,
    exxon: ImpactLevel.MEDIUM,
    exxonmobil: ImpactLevel.MEDIUM,
    chevron: ImpactLevel.MEDIUM,
    shell: ImpactLevel.MEDIUM,
    bp: ImpactLevel.MEDIUM,
    totalenergies: ImpactLevel.MEDIUM,
    petrodollar: ImpactLevel.HIGH,
    'oil embargo': ImpactLevel.HIGH,
    'gas prices': ImpactLevel.HIGH,
    'crack spread': ImpactLevel.MEDIUM,
    refinery: ImpactLevel.MEDIUM,
    iea: ImpactLevel.HIGH,
    'international energy agency': ImpactLevel.HIGH,
    'energy transition': ImpactLevel.MEDIUM,
    'renewable energy': ImpactLevel.MEDIUM,
    'solar energy': ImpactLevel.MEDIUM,

    // ═══════════════════════════════════════════════
    //  GEOPOLITICS
    // ═══════════════════════════════════════════════
    'middle east': ImpactLevel.HIGH,
    'russia ukraine': ImpactLevel.CRITICAL,
    'ukraine war': ImpactLevel.CRITICAL,
    nato: ImpactLevel.HIGH,
    taiwan: ImpactLevel.CRITICAL,
    'taiwan strait': ImpactLevel.CRITICAL,
    china: ImpactLevel.CRITICAL,
    'xi jinping': ImpactLevel.HIGH,
    'north korea': ImpactLevel.HIGH,
    iran: ImpactLevel.HIGH,
    israel: ImpactLevel.HIGH,
    hamas: ImpactLevel.HIGH,
    houthi: ImpactLevel.HIGH,
    'red sea': ImpactLevel.HIGH,
    'strait of hormuz': ImpactLevel.CRITICAL,
    'suez canal': ImpactLevel.HIGH,
    ceasefire: ImpactLevel.HIGH,
    'peace deal': ImpactLevel.HIGH,
    war: ImpactLevel.CRITICAL,
    'military conflict': ImpactLevel.HIGH,
    'geopolitical risk': ImpactLevel.HIGH,
    nuclear: ImpactLevel.CRITICAL,
    'missile test': ImpactLevel.HIGH,
    'sanctions relief': ImpactLevel.HIGH,
    'trade embargo': ImpactLevel.HIGH,
    'us china trade': ImpactLevel.HIGH,
    g7: ImpactLevel.HIGH,
    g20: ImpactLevel.HIGH,
    'united nations': ImpactLevel.MEDIUM,
    'un security council': ImpactLevel.MEDIUM,
    wto: ImpactLevel.MEDIUM,
    'world trade organization': ImpactLevel.MEDIUM,
    election: ImpactLevel.HIGH,
    'us election': ImpactLevel.CRITICAL,
    'presidential election': ImpactLevel.CRITICAL,
    'election result': ImpactLevel.HIGH,
    'political uncertainty': ImpactLevel.HIGH,
    coup: ImpactLevel.HIGH,
    'regime change': ImpactLevel.HIGH,
    terrorism: ImpactLevel.HIGH,
    'cyber attack': ImpactLevel.HIGH,

    // ═══════════════════════════════════════════════
    //  DOLLAR / FOREX
    // ═══════════════════════════════════════════════
    dxy: ImpactLevel.CRITICAL,
    'dollar index': ImpactLevel.CRITICAL,
    usd: ImpactLevel.CRITICAL,
    eur: ImpactLevel.HIGH,
    eurusd: ImpactLevel.HIGH,
    'eur/usd': ImpactLevel.HIGH,
    jpy: ImpactLevel.HIGH,
    usdjpy: ImpactLevel.HIGH,
    'usd/jpy': ImpactLevel.HIGH,
    gbp: ImpactLevel.HIGH,
    gbpusd: ImpactLevel.HIGH,
    'gbp/usd': ImpactLevel.HIGH,
    cad: ImpactLevel.MEDIUM,
    aud: ImpactLevel.MEDIUM,
    chf: ImpactLevel.MEDIUM,
    'carry trade': ImpactLevel.HIGH,
    'yen carry': ImpactLevel.HIGH,
    'dollar strength': ImpactLevel.HIGH,
    'dollar weakness': ImpactLevel.HIGH,
    'fx intervention': ImpactLevel.HIGH,
    'currency intervention': ImpactLevel.HIGH,
    brics: ImpactLevel.HIGH,
    'reserve currency': ImpactLevel.HIGH,
    'dollar hegemony': ImpactLevel.HIGH,
    'currency war': ImpactLevel.HIGH,
    'dollar swap line': ImpactLevel.HIGH,
    'fx reserve': ImpactLevel.MEDIUM,

    // ═══════════════════════════════════════════════
    //  EQUITY MARKETS / INDICES
    // ═══════════════════════════════════════════════
    sp500: ImpactLevel.HIGH,
    's&p 500': ImpactLevel.HIGH,
    nasdaq: ImpactLevel.HIGH,
    'dow jones': ImpactLevel.HIGH,
    'russell 2000': ImpactLevel.MEDIUM,
    vix: ImpactLevel.CRITICAL,
    'volatility index': ImpactLevel.CRITICAL,
    'earnings season': ImpactLevel.HIGH,
    'earnings beat': ImpactLevel.HIGH,
    'earnings miss': ImpactLevel.HIGH,
    'revenue guidance': ImpactLevel.HIGH,
    'profit warning': ImpactLevel.HIGH,
    'earnings revision': ImpactLevel.HIGH,
    'pe ratio': ImpactLevel.MEDIUM,
    'equity risk premium': ImpactLevel.HIGH,
    'stock buyback': ImpactLevel.MEDIUM,
    'share repurchase': ImpactLevel.MEDIUM,
    'dividend cut': ImpactLevel.MEDIUM,
    'dividend increase': ImpactLevel.LOW,
    ipo: ImpactLevel.MEDIUM,
    merger: ImpactLevel.MEDIUM,
    acquisition: ImpactLevel.MEDIUM,
    spinoff: ImpactLevel.LOW,
    'short seller': ImpactLevel.MEDIUM,
    'short selling': ImpactLevel.MEDIUM,
    'gamma squeeze': ImpactLevel.HIGH,
    'options expiry': ImpactLevel.MEDIUM,
    'market breadth': ImpactLevel.MEDIUM,
    'advance decline': ImpactLevel.LOW,
    nikkei: ImpactLevel.MEDIUM,
    dax: ImpactLevel.MEDIUM,
    ftse: ImpactLevel.MEDIUM,
    'cac 40': ImpactLevel.MEDIUM,
    'hang seng': ImpactLevel.HIGH,
    'shanghai composite': ImpactLevel.HIGH,

    // ═══════════════════════════════════════════════
    //  TECH COMPANIES (MARKET MOVERS)
    // ═══════════════════════════════════════════════
    apple: ImpactLevel.HIGH,
    aapl: ImpactLevel.HIGH,
    nvidia: ImpactLevel.HIGH,
    nvda: ImpactLevel.HIGH,
    microsoft: ImpactLevel.HIGH,
    msft: ImpactLevel.HIGH,
    google: ImpactLevel.HIGH,
    alphabet: ImpactLevel.HIGH,
    meta: ImpactLevel.HIGH,
    amazon: ImpactLevel.HIGH,
    amzn: ImpactLevel.HIGH,
    tesla: ImpactLevel.HIGH,
    tsla: ImpactLevel.HIGH,
    'elon musk': ImpactLevel.HIGH,
    openai: ImpactLevel.HIGH,
    'artificial intelligence': ImpactLevel.HIGH,
    ai: ImpactLevel.HIGH,
    'large language model': ImpactLevel.MEDIUM,
    llm: ImpactLevel.MEDIUM,
    semiconductor: ImpactLevel.HIGH,
    'chip shortage': ImpactLevel.HIGH,
    'taiwan semiconductor': ImpactLevel.HIGH,
    tsmc: ImpactLevel.HIGH,
    intel: ImpactLevel.MEDIUM,
    amd: ImpactLevel.MEDIUM,
    arm: ImpactLevel.MEDIUM,
    'data center': ImpactLevel.MEDIUM,
    'cloud computing': ImpactLevel.MEDIUM,
    'tech layoffs': ImpactLevel.MEDIUM,

    // ═══════════════════════════════════════════════
    //  TECHNICAL ANALYSIS SIGNALS
    // ═══════════════════════════════════════════════
    'death cross': ImpactLevel.HIGH,
    'golden cross': ImpactLevel.HIGH,
    'support level': ImpactLevel.MEDIUM,
    'resistance level': ImpactLevel.MEDIUM,
    breakout: ImpactLevel.HIGH,
    breakdown: ImpactLevel.HIGH,
    '200-day moving average': ImpactLevel.HIGH,
    '50-day moving average': ImpactLevel.MEDIUM,
    rsi: ImpactLevel.MEDIUM,
    overbought: ImpactLevel.MEDIUM,
    oversold: ImpactLevel.MEDIUM,
    macd: ImpactLevel.LOW,
    fibonacci: ImpactLevel.LOW,
    'head and shoulders': ImpactLevel.MEDIUM,
    'double top': ImpactLevel.MEDIUM,
    'double bottom': ImpactLevel.MEDIUM,
    'cup and handle': ImpactLevel.MEDIUM,
    'bull flag': ImpactLevel.MEDIUM,
    'bear flag': ImpactLevel.MEDIUM,
    'triangle pattern': ImpactLevel.MEDIUM,
    'wedge pattern': ImpactLevel.MEDIUM,
    'volume surge': ImpactLevel.HIGH,
    'low volume': ImpactLevel.LOW,
    'gap up': ImpactLevel.HIGH,
    'gap down': ImpactLevel.HIGH,
    'all-time high': ImpactLevel.HIGH,
    'all time high': ImpactLevel.HIGH,
    ath: ImpactLevel.HIGH,
    'key support': ImpactLevel.MEDIUM,
    'key resistance': ImpactLevel.MEDIUM,
    'price action': ImpactLevel.LOW,
    candlestick: ImpactLevel.LOW,
    doji: ImpactLevel.LOW,
    engulfing: ImpactLevel.MEDIUM,
    divergence: ImpactLevel.MEDIUM,
    momentum: ImpactLevel.MEDIUM,
    'trend reversal': ImpactLevel.HIGH,
    consolidation: ImpactLevel.LOW,
    'range bound': ImpactLevel.LOW,
    sideways: ImpactLevel.LOW,

    // ═══════════════════════════════════════════════
    //  MARKET SENTIMENT / MACRO THEMES
    // ═══════════════════════════════════════════════
    recession: ImpactLevel.CRITICAL,
    'soft landing': ImpactLevel.HIGH,
    'hard landing': ImpactLevel.CRITICAL,
    stagflation: ImpactLevel.HIGH,
    deflation: ImpactLevel.HIGH,
    disinflation: ImpactLevel.HIGH,
    inflation: ImpactLevel.CRITICAL,
    'risk on': ImpactLevel.HIGH,
    'risk off': ImpactLevel.HIGH,
    'risk-on': ImpactLevel.HIGH,
    'risk-off': ImpactLevel.HIGH,
    'flight to safety': ImpactLevel.HIGH,
    'flight to quality': ImpactLevel.HIGH,
    panic: ImpactLevel.HIGH,
    fud: ImpactLevel.HIGH,
    'fear uncertainty doubt': ImpactLevel.HIGH,
    'black swan': ImpactLevel.CRITICAL,
    contagion: ImpactLevel.CRITICAL,
    'market crash': ImpactLevel.CRITICAL,
    correction: ImpactLevel.HIGH,
    'bear market': ImpactLevel.HIGH,
    'bull market': ImpactLevel.HIGH,
    'market rally': ImpactLevel.HIGH,
    'sell-off': ImpactLevel.HIGH,
    selloff: ImpactLevel.HIGH,
    liquidity: ImpactLevel.HIGH,
    'credit crunch': ImpactLevel.CRITICAL,
    'credit spread': ImpactLevel.HIGH,
    'junk bond': ImpactLevel.HIGH,
    'high yield': ImpactLevel.HIGH,
    'investment grade': ImpactLevel.MEDIUM,
    deleveraging: ImpactLevel.HIGH,
    'margin call': ImpactLevel.HIGH,
    'forced selling': ImpactLevel.HIGH,
    capitulation: ImpactLevel.HIGH,
    'dead cat bounce': ImpactLevel.MEDIUM,
    'relief rally': ImpactLevel.MEDIUM,
    'momentum shift': ImpactLevel.MEDIUM,
    'sentiment shift': ImpactLevel.MEDIUM,
    fomo: ImpactLevel.MEDIUM,
    'profit taking': ImpactLevel.MEDIUM,
    'position squaring': ImpactLevel.MEDIUM,
    'stop loss': ImpactLevel.MEDIUM,
    'stop hunt': ImpactLevel.MEDIUM,
    'thin liquidity': ImpactLevel.MEDIUM,
    'holiday trading': ImpactLevel.LOW,
    'seasonal pattern': ImpactLevel.LOW,
};
