export const TrainData = {
    // ─────────────────────────────────────────────
    //  GOLD
    // ─────────────────────────────────────────────
    BULLISH_GOLD: [
        // Monetary policy
        'Fed cuts interest rates by 50 basis points',
        'Fed signals pause in rate hike cycle',
        'FOMC minutes reveal dovish tilt among members',
        'Fed Chair hints at rate cuts in upcoming quarters',
        'Central bank adopts accommodative monetary policy stance',
        'Negative real interest rates fuel gold demand',
        'Bond yields turn negative in Germany and Japan',
        'Fed balance sheet expansion reignites inflation fears',
        'Yields on 10-year Treasury fall, supporting gold prices',
        'Fed pivot expected as labor market cools sharply',
        // Macro / inflation
        'Inflation fears drive investors toward safe-haven gold',
        'CPI print comes in hotter than expected, gold rallies',
        'Stagflation scenario boosts demand for hard assets',
        'Global recession risks push gold above key resistance',
        'US debt ceiling crisis spooks bond markets, gold climbs',
        'Budget deficit widens to record levels, gold surges',
        'Government announces new fiscal stimulus package',
        'Supply chain disruptions reignite inflation concerns',
        'Producer price index jumps unexpectedly, gold gains',
        'Real yields drop to multi-month lows, gold benefits',
        // Geopolitics
        'Gold prices surge amid geopolitical tensions in Middle East',
        'Russia-Ukraine conflict escalates, safe-haven demand rises',
        'NATO allies increase defense spending, gold spikes',
        'North Korea missile test rattles global markets',
        'Israel-Hamas conflict widens to regional proxy war',
        'Sanctions on major oil producer trigger risk-off mood',
        'Taiwan Strait tensions push investors to gold',
        'Terror attack on major city triggers flight to safety',
        'Global diplomatic tensions reach highest level in decades',
        'UN emergency session called over conflict, gold jumps',
        // Dollar / currency
        'Dollar Index (DXY) hits 1-year low, boosting XAU',
        'USD weakens after disappointing jobs data',
        'Dollar slides as twin deficit concerns mount',
        'De-dollarization trend supports long-term gold rally',
        'BRICS nations announce gold-backed trade settlement',
        'Dollar loses reserve currency status in key bilateral deals',
        'Emerging market currencies collapse, dollar weakens',
        'US current account deficit widens unexpectedly',
        'Currency crisis in major economy boosts safe-haven flows',
        'Yen carry trade unwinds, gold attracts capital',
        // Demand / institutional
        'Central banks increase gold reserves at record pace',
        "China People's Bank of China adds 30 tonnes to gold reserves",
        'India central bank repatriates gold held overseas',
        'Gold ETFs see massive inflows as market uncertainty grows',
        'Hedge funds increase net-long gold positions sharply',
        'Warren Buffett disclosures show new gold mining stake',
        'Sovereign wealth funds diversify into gold allocations',
        'Family offices rotate from bonds to gold',
        'Pension funds raise gold allocation to 5% of portfolio',
        'Record physical gold purchases by retail investors in Asia',
        // Technical / market structure
        'Gold breaks above $2,100 resistance with strong volume',
        'XAU/USD golden cross forms on weekly chart',
        'Gold consolidates above 200-day moving average',
        'Options market shows heavy call buying in gold futures',
        'Gold futures open interest surges to record high',
        'Short squeeze propels gold above key technical level',
    ],

    BEARISH_GOLD: [
        // Monetary policy
        'Fed signals higher-for-longer interest rate path',
        'Fed raises rates by 75 basis points, gold tumbles',
        'FOMC minutes show unanimous support for further hikes',
        'Fed Chair rules out rate cuts for the rest of the year',
        'Real yields climb to highest level in 15 years',
        'Bank of England surprises with aggressive rate hike',
        'ECB signals multiple additional rate increases ahead',
        'Bank of Japan abandons yield curve control, JGB yields surge',
        'Treasury yields jump as economy shows robust growth',
        'Hawkish Fed rhetoric crushes gold momentum',
        // Macro
        'Inflation cooling faster than expected, gold loses appeal',
        'GDP growth beats forecasts, risk appetite improves',
        'Strong NFP report suggests Fed will keep rates high',
        'Retail sales data surprises to the upside',
        'PMI composite reading signals economic acceleration',
        'US economy avoids recession, gold premium fades',
        'Debt ceiling deal reached, risk-off trade reverses',
        'IMF upgrades global growth forecast, gold retreats',
        'Disinflation accelerates in the eurozone',
        'Consumer confidence surges to multi-year high',
        // Dollar / currency
        'Strong US Dollar puts pressure on gold prices',
        'DXY recovers sharply, XAU/USD breaks below support',
        'Dollar strengthens after hawkish Fed commentary',
        'Euro collapses on recession fears, dollar surges',
        'Yen weakens sharply, dollar index spikes higher',
        'Dollar demand rises on safe-haven status during equity rally',
        'US trade deficit narrows, supporting dollar bulls',
        'Dollar index climbs above 107, gold feels the pressure',
        'Carry traders increase dollar long positions',
        'Dollar dominance reinforced as reserve currency',
        // Geopolitics
        'Peace talks reduce geopolitical risk premium for gold',
        'Ceasefire agreement signed in Middle East conflict',
        'Diplomatic breakthrough reduces nuclear tensions',
        'G20 summit ends with landmark trade cooperation deal',
        'Russia-Ukraine ceasefire reduces safe-haven demand',
        'Global leaders agree on security framework, risk-off eases',
        'Terrorist threat neutralized, markets stabilize',
        'UN resolution passes, reducing escalation risk',
        'Geopolitical risk index falls to multi-year low',
        'Trade war tariffs rolled back in bilateral agreement',
        // Demand / outflows
        'Profit-taking hits gold after recent all-time highs',
        'Investors dump gold for riskier assets like stocks',
        'Gold ETF holdings fall for sixth consecutive week',
        'Retail demand for gold in India and China drops',
        'Hedge funds cut net-long gold exposure significantly',
        'Central bank gold buying slows to multi-year lows',
        'Gold mining stocks underperform broad market',
        'Speculative longs in COMEX gold futures are liquidated',
        'Physical gold premiums in Asia collapse on weak demand',
        'Jewelry demand falls sharply as prices remain elevated',
        // Technical
        'XAU/USD breaks below critical $1,900 support level',
        'Death cross forms on gold daily chart',
        'Gold fails to hold above 50-day moving average',
        'Technical selling accelerates below $1,950',
        'Gold options skew shifts bearish with put buying surge',
    ],

    // ─────────────────────────────────────────────
    //  CRYPTO
    // ─────────────────────────────────────────────
    BULLISH_CRYPTO: [
        // Regulation / institutional
        'SEC approves first spot Bitcoin ETF for major banks',
        'US Congress passes pro-crypto framework legislation',
        'EU MiCA regulation provides clarity for crypto firms',
        'Major sovereign wealth fund discloses Bitcoin holdings',
        'BlackRock files for spot Ethereum ETF',
        'Fidelity launches institutional crypto custody service',
        'Goldman Sachs opens crypto trading desk for clients',
        'JPMorgan settles interbank payments on blockchain',
        'Nasdaq launches regulated Bitcoin futures market',
        'G20 adopts unified crypto asset classification standard',
        // Adoption / fundamentals
        'Bitcoin halving reduces supply, driving prices higher',
        'Major tech company adds BTC to corporate balance sheet',
        'Lightning Network expansion improves Bitcoin utility',
        'El Salvador reports BTC treasury gains of 40%',
        'Second nation announces Bitcoin as legal tender',
        'Global remittance volume on Bitcoin network surges',
        'Active Bitcoin addresses hit all-time high',
        'Bitcoin miner revenue breaks quarterly record',
        'Layer-2 scaling solutions boost ETH network activity',
        "Ethereum's deflationary burn mechanism accelerates",
        // DeFi / ecosystem
        'Institutional adoption of Ethereum reaches new peak',
        'Total value locked in DeFi surpasses previous record',
        'Major bank integrates DeFi lending protocol',
        'NFT market volume rebounds sharply after slowdown',
        'Cross-chain bridge volume reaches all-time high',
        'Stablecoin market cap grows 30% in single quarter',
        'Decentralized exchange volume overtakes centralized peers',
        'Smart contract auditing firms report zero critical bugs in major protocol',
        'Ethereum staking yield attracts fresh institutional capital',
        'Layer-2 daily transactions exceed Ethereum mainnet',
        // Macro / market
        'Whale accumulation of BTC increases significantly',
        'Bitcoin supply on exchanges drops to 5-year low',
        'Bitcoin hash rate reaches all-time high',
        'On-chain data shows long-term holder accumulation surge',
        'Fear & Greed Index flips to extreme greed territory',
        'Risk-on sentiment drives capital rotation into crypto',
        'Crypto venture capital funding hits quarterly record',
        'Global banks start offering crypto custody services',
        'Positive regulatory framework proposed for digital assets',
        'Spot BTC ETF records highest single-day inflow',
        // Technical
        'Bitcoin breaks above $100,000 on massive volume',
        'BTC weekly chart shows clean breakout above resistance',
        'Altcoin season begins as BTC dominance drops below 40%',
        'Ethereum completes major upgrade improving efficiency',
        'On-chain metrics show market bottom formation',
        'BTC 200-week moving average acts as strong support',
        'Options market shows record call open interest for BTC',
        'Bitcoin futures premium turns positive, signaling bullish sentiment',
        'Crypto market cap recovers above $3 trillion',
        'Solana breaks multi-month resistance, bulls take charge',
    ],

    BEARISH_CRYPTO: [
        // Regulation / legal
        'SEC launches investigation into major crypto exchange',
        'US Treasury designates crypto mixer as money-laundering tool',
        'DOJ charges top exchange CEO with fraud',
        'G7 nations agree on coordinated crypto crackdown',
        'China reiterates total ban on all crypto activities',
        'India imposes 30% tax on crypto gains with no deductions',
        'EU regulators freeze assets of major stablecoin issuer',
        'CFTC sues leading DeFi protocol for illegal derivatives',
        'Congressional hearing turns hostile toward crypto industry',
        'Regulatory uncertainty causes institutional outflow',
        // Security / hacks
        'Exchange hack leads to millions in stolen ETH',
        'DeFi protocol exploited for $500M through smart contract bug',
        'Cross-chain bridge suffers critical vulnerability exploit',
        'Rug pull by anonymous dev wipes out $200M in liquidity',
        'Stablecoin depegs from $1, triggering cascading liquidations',
        'Major NFT marketplace suffers phishing attack on users',
        'Crypto custodian reports unauthorized withdrawal of funds',
        'Private key compromise leads to total loss of exchange reserves',
        'Flash loan attack drains lending protocol reserves',
        'Consensus layer vulnerability discovered in popular blockchain',
        // Market structure
        'Massive liquidation of long positions triggers flash crash',
        'Whale dump causes 10% drop in BTC price',
        'Bitcoin fails to break $70k resistance, bears take over',
        'Fear, Uncertainty, and Doubt grows over stablecoins',
        'Crypto market loses $500B in 48 hours on macro shock',
        'Leverage ratio on exchanges hits dangerous highs before sell-off',
        'Bitcoin miner capitulation triggers further downside',
        'Contagion from exchange bankruptcy spreads to lenders',
        'Stablecoin redemptions cause liquidity crisis across DeFi',
        'Short sellers increase positions on all major crypto assets',
        // Macro
        'Risk-off sentiment hits crypto harder than equities',
        'Federal Reserve tightening drains liquidity from crypto',
        'Dollar index surge crushes all dollar-denominated assets including BTC',
        'Global recession fears trigger flight from speculative assets',
        'Institutional funds redeem crypto allocations for cash',
        'Crypto venture funding drops 70% amid funding winter',
        'High transaction fees stall DeFi growth on Ethereum',
        'Central Bank warns against crypto as a legal tender',
        'Pension fund divests entire crypto allocation',
        'Yield on Treasury bonds makes crypto risk-reward unattractive',
        // Technical
        'Bitcoin drops below 200-week moving average for first time',
        'BTC death cross confirmed on daily chart',
        'Crypto Fear & Greed Index hits extreme fear level',
        'Ethereum breaks critical $1,500 support with rising volume',
        'Bitcoin weekly close below $40,000 confirms bearish trend',
        'On-chain data shows capitulation by long-term holders',
        'Open interest collapses as traders exit crypto derivatives',
        'Funding rates deeply negative, short sellers dominate',
        'BTC dominance surges as altcoins see accelerated losses',
        'Market-wide sell signal triggered on monthly RSI',
    ],

    // ─────────────────────────────────────────────
    //  NEUTRAL / SIDEWAYS
    // ─────────────────────────────────────────────
    NEUTRAL: [
        'Market awaits FOMC meeting minutes for direction',
        'Stock markets trade sideways ahead of earnings season',
        'Oil prices stabilize as OPEC maintains production levels',
        'Trading volume remains low during holiday session',
        'Investors monitor global trade developments closely',
        'Consumer confidence index stays unchanged this month',
        "Housing starts data meets economists' expectations",
        'Currency markets show minimal volatility in morning trade',
        'Technical correction observed after minor price rally',
        'Quarterly GDP growth aligns with previous forecasts',
        'Markets pause ahead of key central bank decision',
        'Range-bound trading continues as catalysts are absent',
        'Mixed economic signals prevent directional move',
        'Low-volume session as US traders observe bank holiday',
        'Traders square positions ahead of the weekend',
        'Market waits for next inflation data print before moving',
        'Options expiry creates pinning effect near current levels',
        'Conflicting analyst reports keep investors on the sidelines',
        'Volatility index (VIX) remains muted near historical lows',
        'Futures market shows flat open for major indices',
        'Cross-asset correlation breaks down, no clear trend',
        'Institutional flows balanced between buyers and sellers',
        'Lack of macro catalyst keeps price action compressed',
        "Market digests last week's data before next catalyst",
        'Bid-ask spreads widen slightly on thin liquidity conditions',
        'Price action consolidates between key support and resistance',
        'Traders await Fed speaker commentary later in the session',
        'Earnings season begins with mixed results from early reporters',
        'Global PMI data shows modest expansion, in line with forecasts',
        'Technical indicators show neither overbought nor oversold levels',
        'Currency pairs trade in tight ranges during Asian session',
        'Commodity markets drift as supply and demand stay balanced',
        'Retail sales figure lands exactly at median forecast',
        'Weekly jobless claims unchanged at expected levels',
        'Bond market remains calm ahead of Treasury auction',
        'Market breadth neutral with equal advancing and declining stocks',
        'No major economic events scheduled for the rest of the week',
        'Quiet trading session with minimal institutional activity',
        'Gold and equities move in tandem, showing no clear divergence',
        'Index futures hovering near prior close with little movement',
        'Trade balance data shows modest improvement, no surprises',
        'Durable goods orders in line with consensus estimate',
        'Central bank holds rates steady as expected by all economists',
        'Markets show wait-and-see approach ahead of G20 summit',
        'Implied volatility near historical average, no fear or greed',
        'Sector rotation continues but does not produce net market move',
        'Market makers keep spreads tight, liquidity is normal',
        'Seasonal adjustment clouds interpretation of economic data',
        'Analyst consensus remains split between bull and bear cases',
        'Price discovery phase continues with no dominant direction',
    ],

    // ─────────────────────────────────────────────
    //  BULLISH OIL (WTI / BRENT)
    // ─────────────────────────────────────────────
    BULLISH_OIL: [
        'OPEC+ announces surprise 1 million barrel per day production cut',
        'Saudi Arabia extends voluntary production cut indefinitely',
        'US crude oil inventories fall sharply below expectations',
        'China reopens economy, driving fuel demand surge',
        'Houthi attacks disrupt Red Sea tanker routes',
        'Russia voluntarily cuts oil exports by 500,000 barrels per day',
        'Tropical storm forces closure of Gulf of Mexico platforms',
        'US shale output growth stalls due to lack of capital spending',
        'Global jet fuel demand hits post-pandemic record high',
        'Strategic petroleum reserve replenishment announced by US',
        'Winter heating demand spikes on colder-than-expected forecasts',
        'Middle East conflict threatens key oil transit chokepoint',
        'Libya production offline due to internal political conflict',
        'Nigeria pipeline sabotage reduces Atlantic basin supply',
        'Refinery utilization rates hit multi-year highs',
        'Venezuela sanctions tightened, further reducing exports',
        'Iran sanctions enforcement increases, crude flows drop',
        'OPEC spare capacity at lowest level in a decade',
        'IEA revises global demand forecast sharply higher',
        'China strategic reserve buying accelerates',
        'Brent crude breaks above $90 resistance with strong momentum',
        'Energy sector earnings beat forecasts, sector leadership continues',
        'Diesel crack spreads widen to record levels',
        'Geopolitical risk premium returns to oil markets',
        'US rig count falls for seventh consecutive week',
        'Supply disruptions in Kazakhstan cut output significantly',
        'Angola leaves OPEC, adding uncertainty to cartel supply plans',
        'Freight rates on oil tanker routes double on demand surge',
        'Energy transition slower than expected, fossil fuel demand holds',
        'WTI crude futures open interest rises sharply with price',
        'Iraq federal government and Kurdistan region halt joint exports',
        'Russian oil price cap enforcement softens, export volumes shrink',
        'Global oil demand growth led by aviation and petrochemicals',
        'Heating oil futures hit seasonal high on cold snap forecast',
        'Oil majors reduce capex, signaling tighter future supply',
        'Gasoline demand spikes ahead of summer driving season',
        'EV adoption slower than projected, oil demand stays high',
        'Brazilian pre-salt output misses government target',
        'North Sea maintenance season reduces European supply',
        'Oil market structural deficit now forecast through year-end',
        'Backwardation in crude futures signals immediate supply tightness',
        'Shell warns of lower-than-expected production in quarterly update',
        'Energy minister of Saudi Arabia signals commitment to price floor',
        'Hedge funds increase net-long crude positions to 6-month high',
        'Tanker tracking data shows significant drop in visible supply',
        'China crude import volumes hit record in October',
        'Analyst upgrades WTI price target to $100',
        'US export terminals operating at full capacity',
        'Seasonal demand for crude oil accelerates into Q4',
        'Norwegian oil workers strike threatens North Sea output',
    ],

    BEARISH_OIL: [
        'OPEC+ agrees to increase production by 500,000 barrels per day',
        'Saudi Arabia threatens to unleash full production capacity',
        'US crude inventories rise for fifth consecutive week',
        'Global recession fears crush oil demand outlook',
        'China economic data disappoints, fuel demand growth revised lower',
        'Ceasefire in Middle East reduces geopolitical risk premium',
        'US shale output hits record high, flooding the market',
        'IEA warns of significant oil oversupply in second half of year',
        'OPEC+ unity fractures as UAE pushes for higher output quota',
        'Strategic petroleum reserve release floods market with supply',
        'Russia bypasses oil price cap, flooding Asian markets',
        'Mild winter reduces heating fuel demand across Europe',
        'Global EV sales surge reduces long-term oil demand outlook',
        'Refiners cut utilization rates as margins collapse',
        'Libyan National Oil Corporation restores full production',
        'Iran nuclear deal revived, unlocking 1.5 million barrels per day',
        'Nigeria pipeline restored, boosting Atlantic basin supply',
        'Demand destruction accelerates as gasoline prices hit records',
        'Weak manufacturing PMI signals slowdown in industrial fuel use',
        'Cargo vessels divert away from Red Sea routes, costs ease',
        'Gasoline crack spreads collapse, reducing refinery margins',
        'Venezuela production recovers after sanctions relief',
        'US oil exports surge on weak domestic demand',
        'Oil market surplus forecast widening into 2025',
        'WTI breaks below $70 key support level',
        'Energy demand in Europe falls sharply on warm autumn',
        'Airlines report lower-than-expected fuel burn in Q3',
        'Natural gas substitution reduces oil consumption in power sector',
        'IMF cuts global growth forecast, dragging oil demand outlook',
        'OPEC internal dispute delays communiqué at ministerial meeting',
        'US rig count rises sharply, signaling output acceleration',
        'Cushing Oklahoma inventory surges to 6-month high',
        'Hedge funds liquidate crude futures longs en masse',
        'Brent crude falls below 200-day moving average',
        'Death cross confirmed on WTI daily chart',
        'Tanker rates collapse as supply outpaces demand',
        'US biofuel mandate expansion reduces petroleum demand',
        'China imports fall as domestic refinery throughput cuts back',
        'Oil futures curve moves into contango, signaling oversupply',
        'Mexico Pemex production hits 20-year low despite investment',
        'Global shipping slowdown reduces maritime fuel demand',
        'Coal-to-liquids substitution accelerates in Asia',
        'Warm El Niño winter forecast reduces heating oil demand',
        'Carbon tax hikes accelerate industrial fuel switching',
        'Recessionary signals from yield curve inversion weigh on crude',
        'US Federal Reserve tightening kills energy capex spending',
        'Profit-taking accelerates below $80 after failed breakout',
        'Russia and Saudi Arabia publicly disagree on OPEC+ cuts',
        'Oil demand growth revised to zero for 2025 by major analyst',
        'Crude carry traders unwind positions on weakening fundamentals',
    ],

    // ─────────────────────────────────────────────
    //  BULLISH EQUITIES (S&P 500 / GLOBAL STOCKS)
    // ─────────────────────────────────────────────
    BULLISH_EQUITIES: [
        'Fed pivot signals end of rate hike cycle, equities rally',
        'S&P 500 earnings season beats consensus by widest margin in years',
        'US unemployment rate falls to 50-year low',
        'Tech megacaps report blowout quarterly results',
        'AI-driven productivity boom reshapes earnings outlook',
        'Federal Reserve balance sheet expansion lifts all risk assets',
        'Inflation falls to 2% target, removing policy headwind',
        'Consumer spending beats forecasts for third consecutive month',
        'Bank stress tests passed by all major US financial institutions',
        'IPO market reopens with string of oversubscribed listings',
        'S&P 500 breaks all-time high on broad-based participation',
        'VIX drops below 12, reflecting extreme market complacency',
        'Short covering accelerates after major index breakout',
        'Manufacturing ISM rebounds sharply from contraction territory',
        'Strong holiday retail sales signal robust consumer health',
        'Mergers and acquisitions activity surges in banking sector',
        'Share buyback announcements hit quarterly record',
        'Dividend hikes announced by majority of Dow 30 companies',
        'Soft landing narrative gains credibility with latest data',
        'Corporate profit margins expand despite cost pressures',
        'Global trade volumes recover after multi-year contraction',
        'European Central Bank signals end to rate hike cycle',
        'China stimulus package worth $1 trillion announced',
        'MSCI Emerging Markets index breaks out of 2-year range',
        'Nikkei 225 hits 30-year high on yen weakness and exports',
        'Semiconductor cycle recovery drives tech sector outperformance',
        'Healthcare sector rallies on FDA fast-track drug approvals',
        'Energy transition capex boom lifts industrials and materials',
        'Risk appetite surges as credit spreads tighten sharply',
        'Passive fund inflows hit monthly record, supporting indices',
        'Options gamma squeeze propels index higher into expiry',
        'Federal budget deal removes fiscal cliff uncertainty',
        'University endowments increase equity allocation by 5%',
        'Sovereign wealth funds announce large equity purchases',
        'Small-cap stocks outperform on domestic growth optimism',
        'Equal-weight S&P 500 outperforms, showing broad participation',
        'AI infrastructure spending drives cloud provider revenue beats',
        'Biotech rally led by breakthrough cancer drug approval',
        'Homebuilder stocks surge as mortgage rates begin to fall',
        'Consumer discretionary sector leads on strong wage growth',
        'Transportation index breaks out, confirming economic expansion',
        'Cyclical stocks rotate into leadership on recovery signals',
        'Market internals strongest in two years with majority new highs',
        'Earnings revisions turn positive for first time in six quarters',
        'Global PMI composite returns to expansion territory',
        'Retail investor sentiment turns bullish, AAII survey shows',
        'Tax cut extension passed by Congress, boosts after-tax earnings',
        'S&P 500 forward P/E compression ends as growth re-accelerates',
        'Buyout activity in small-cap space accelerates significantly',
        'Quarterly GDP revised sharply higher, confirming soft landing',
    ],

    BEARISH_EQUITIES: [
        'Yield curve inversion deepens, recession probability rises to 70%',
        'S&P 500 earnings recession confirmed for second consecutive quarter',
        'Fed delivers surprise rate hike, crushing equity valuations',
        'Credit spreads blow out as corporate default rate climbs',
        'Regional bank crisis spreads to larger financial institutions',
        'Inflation re-accelerates, forcing Fed to abandon pivot',
        'US government shutdown begins, dragging on economic activity',
        'Trade war tariffs escalate to cover all major import categories',
        'Major tech company misses earnings, sector sells off broadly',
        'VIX spikes above 30 as risk-off sentiment dominates',
        'Margin calls force institutional de-leveraging across portfolios',
        'Global growth downgrade by IMF triggers broad equity sell-off',
        'Oil price spike threatens corporate profit margins',
        'Commercial real estate crisis spreads to bank balance sheets',
        'Consumer delinquency rates hit 10-year highs',
        'Unemployment rate jumps unexpectedly, recession fears grow',
        'Forward earnings estimates revised lower for full year',
        'Geopolitical shock triggers global risk-off episode',
        'China property market collapse triggers contagion fears',
        'US government credit rating downgraded by major agency',
        'Liquidity crisis in money markets requires Fed intervention',
        'Major hedge fund liquidation hits crowded long positions',
        'Earnings guidance cut across technology and consumer sectors',
        'Fed chair says rates will stay higher for much longer',
        'Flash crash wipes 5% from S&P 500 in under an hour',
        'Retail investor sentiment collapses to extreme fear',
        'Quantitative tightening accelerates, removing market liquidity',
        'Auto sector hit by combination of weak demand and EV transition',
        'Housing starts collapse to 2009 levels',
        'Profit margins compress as wage inflation remains sticky',
        'Semiconductors enter inventory correction with no clear end date',
        'IPO market freezes as risk appetite disappears',
        'Leveraged buyout deals fail to close on tighter credit conditions',
        'Bond vigilantes force sharp repricing in equity multiples',
        'S&P 500 breaks below 200-day moving average on high volume',
        'Death cross confirmed for Nasdaq composite index',
        'Dividend cuts announced by key consumer staples companies',
        'Sovereign debt crisis in Europe rattles global equity markets',
        'Manufacturing recession confirmed, PMI below 50 for six months',
        'Risk parity funds forced to sell equities as correlations break',
        'Buyback moratorium proposed by Congress, removing demand pillar',
        'Share issuance wave from distressed companies dilutes shareholders',
        'Major pension fund announces reduction in equity allocation',
        'Equity risk premium falls to historical low, valuation stretched',
        'Technical breakdown below neckline in head-and-shoulders pattern',
        'Breadth deteriorates sharply with 80% of stocks below 50-day MA',
        'Global supply chain shock creates profit warning wave',
        'Bank of Japan policy normalization triggers yen carry unwind',
        'Asset manager reports record redemptions from equity funds',
        'Insider selling at largest US companies hits multi-year high',
    ],

    // ─────────────────────────────────────────────
    //  FOREX  — USD BULLISH (DXY UP)
    // ─────────────────────────────────────────────
    BULLISH_USD: [
        'Fed signals further rate hikes, dollar demand spikes',
        'US GDP growth outpaces all G10 peers by wide margin',
        'Strong NFP print reinforces dollar bullish narrative',
        'US inflation re-accelerates, forcing hawkish Fed response',
        'Safe-haven dollar demand surges on global risk-off event',
        'DXY breaks above 107, momentum accelerates to upside',
        'US trade balance improves, reducing dollar supply pressure',
        'Fed Chair rules out rate cuts in any near-term meeting',
        'US manufacturing rebounds, supporting cyclical dollar strength',
        'European recession deepens, euro collapses against dollar',
        'Bank of Japan intervenes to weaken yen, dollar soars',
        'Emerging market currency crisis boosts safe-haven dollar',
        'US current account deficit narrows, reducing dollar headwind',
        'China capital controls tighten, dollar demand from Asia rises',
        'ECB turns dovish, widening USD-EUR yield differential',
        'US Treasury yields rise to 16-year highs, attracting capital',
        'Global investors repatriate funds to USD-denominated assets',
        'Dollar liquidity shortage in offshore markets sends DXY higher',
        'Risk-off rotation from commodities into US dollar cash',
        'Geopolitical shock sends capital flows into US Treasuries',
        'Dollar index reclaims 50-day moving average with conviction',
        'Fed holds rates while peers cut, widening rate differential',
        'US exceptionalism narrative drives broad dollar strength',
        'Capital flight from eurozone periphery boosts USD demand',
        'Dollar short squeeze after positioning turns crowded',
        'CFTC data shows record speculative dollar long positioning',
        'Dollar seasonality historically strong in Q4',
        'Commodity currencies crushed as China slowdown deepens',
        'Oil price collapse weakens petrodollar recycling flows',
        'Global PMI divergence favors US growth over all peers',
        'Bank of Canada pivots to rate cuts, CAD weakens vs USD',
        'Reserve Bank of Australia signals end of hiking cycle',
        'UK fiscal crisis re-emerges, GBP falls sharply vs USD',
        'Swiss National Bank intervenes to weaken CHF',
        'Dollar rebounds from oversold conditions on technical buying',
        'US services sector dominance supports dollar premium',
        'Hawkish FOMC statement surprises markets, DXY jumps 1%',
        'Dollar strength broadens to include commodity-linked currencies',
        'Options market shows heavy USD call buying across board',
        'Debt ceiling resolved, US creditworthiness reinforced',
        'Fed minutes show consensus for higher terminal rate',
        'US housing market resilience surprises, supports dollar bulls',
        'Stagflation in Europe forces ECB to prioritize growth over rates',
        'Dollar bid increases as year-end repatriation flows begin',
        'Cross-currency swap basis tightens, reflecting USD scarcity',
        'EM central banks sell reserves to defend currencies vs USD',
        'US corporate earnings season beats globally, supporting USD',
        'Strong US productivity data supports dollar premium',
        'Dollar benefits from de-risking across all asset classes',
        'DXY weekly close above 106 confirms resumption of bull trend',
    ],

    BEARISH_USD: [
        'Fed pivots to rate cuts, dollar index falls sharply',
        'US recession confirmed, Fed forced into emergency easing',
        'Twin deficit widening undermines dollar confidence',
        'De-dollarization trend accelerates among BRICS nations',
        'US credit rating downgraded, Treasuries sold aggressively',
        'Fed balance sheet expansion resumes, dollar weakens broadly',
        'Soft US inflation data cements rate cut expectations',
        'DXY falls below 100 for first time in 18 months',
        'US jobs market cracks, dollar demand evaporates',
        'G7 nations discuss coordinated dollar weakening policy',
        'Euro strengthens on ECB rate hikes, EUR/USD tests 1.15',
        'Yen carry trade reversal sends dollar sharply lower',
        'China diversifies reserves away from US Treasuries',
        'OPEC nations settle oil trades in non-dollar currencies',
        'US political dysfunction raises questions over reserve currency',
        'Federal deficit widens, foreign investors reduce Treasury buying',
        'Dollar smile theory breaks down as US growth slows sharply',
        'BRICS launch alternative reserve currency framework',
        'ECB overtakes Fed in hawkishness, EUR leads dollar lower',
        'Risk-on sentiment drives capital away from safe-haven USD',
        'Commodity currencies surge on China reopening, USD sidelined',
        'US debt ceiling brinkmanship shakes foreign reserve holders',
        'Real dollar index falls to multi-decade lows adjusted for inflation',
        'Short USD trade becomes most crowded position in hedge fund surveys',
        'Dollar index death cross forms on weekly chart',
        'Dollar falls as yield advantage over peers narrows significantly',
        'ECB surprise rate hike crushes EUR/USD short positions',
        'Emerging market central banks stop defending currencies, USD falls',
        'US consumer spending weakens, GDP growth at risk',
        'Dollar weakens as US exceptionalism narrative fades',
        'Fed cuts rates despite inflation, markets price dollar negative outlook',
        'USD falls 2% in single session after weak ISM services data',
        'New non-dollar trade settlement system adopted by major exporters',
        'US fiscal stimulus drives inflation, not growth, undermining dollar',
        'JPY strengthens 5% as Bank of Japan normalizes rates',
        'EUR/USD breaks above 1.12 on eurozone recovery surprise',
        'Commodity exporters strengthen as USD reserve share drops',
        'Cross-border payments shift to EUR and CNY in Europe-Asia trade',
        'US political uncertainty ahead of election weighs on dollar',
        'Weak US retail sales confirm consumer slowdown, USD falls',
        'China and Russia bilateral trade moves to local currencies',
        'Dollar correlation with yields breaks down, bearish signal',
        'Net long USD positioning at crowded levels, reversal risk high',
        'IMF calls for reduced reliance on USD in global payments',
        'Weak US housing data adds to economic slowdown concerns',
        'Middle East sovereign funds diversify away from dollar assets',
        'Fed real rate falls below peers, removing dollar yield advantage',
        'US corporate bond spreads widen, risk appetite shifts to EUR assets',
        'Commodity boom inflates non-dollar currencies vs USD',
        'Trade weighted USD index falls to 3-year low',
    ],

    // ─────────────────────────────────────────────
    //  SILVER
    // ─────────────────────────────────────────────
    BULLISH_SILVER: [
        'Solar panel demand drives industrial silver consumption to record',
        'Silver deficit widens as mine supply growth stagnates',
        'Gold-to-silver ratio drops sharply, silver plays catch-up',
        'Electric vehicle production boom lifts silver demand outlook',
        'Green energy transition requires 50% more silver than previously estimated',
        'Fed rate cuts boost silver alongside broader precious metals rally',
        'Silver ETF inflows hit highest level in two years',
        'Mining strike in major silver-producing country reduces supply',
        'Electronics sector demand for silver surpasses industrial forecasts',
        'Silver breaks above $30 resistance, momentum buyers enter',
        'Speculative short squeeze propels silver 15% in single session',
        'India imports record volume of silver for industrial use',
        'Medical applications of silver expand with new antimicrobial research',
        '5G infrastructure rollout accelerates silver demand for electronics',
        'Silver mine grades decline globally, raising production costs',
        'Central banks add silver to commodity reserve diversification strategy',
        'Silver futures open interest surges ahead of options expiry',
        'Silver undervalued relative to gold on historical metrics',
        'Hedge funds begin aggressive accumulation of silver positions',
        'Silver achieves breakout from multi-year base on weekly chart',
        'AI data center cooling systems use silver-coated components',
        'Semiconductor silver paste demand grows 20% in fiscal year',
        'Silver market structural deficit forecasted for next five years',
        'Social media-driven retail buying campaign targets silver market',
        'Physical silver premium rises above 15% over spot price',
        'Bullion dealers report silver sold out at multiple locations',
        'Silver photovoltaic demand doubles on subsidized solar installations',
        'Water purification demand for silver rises in developing markets',
        'Silver coin and bar demand from retail investors hits decade high',
        'Inflation hedge narrative for silver strengthens on CPI data',
    ],

    BEARISH_SILVER: [
        'Industrial demand slows as global manufacturing PMI contracts',
        'Gold-to-silver ratio expands to 90, silver underperforms',
        'Silver ETF holdings fall to 5-year low',
        'Solar panel silver intensity reduced by new thin-film technology',
        'China economic slowdown crushes industrial metals demand',
        'Silver prices fall below cost of production for high-cost miners',
        'Mine supply increases sharply as copper byproduct output rises',
        'Strong dollar makes silver exports expensive for buyers',
        'Fed rate hike cycle raises opportunity cost of holding silver',
        'Silver breaks below $22 support, technical sell-off accelerates',
        'Solar subsidy removal in key market cuts silver demand forecasts',
        'Electronics manufacturers substitute silver with cheaper alternatives',
        'Silver warehouse stocks at exchanges rise to multi-year highs',
        'Speculative long liquidation hits silver futures market',
        'Global recessionary fears crush industrial metals across board',
        'Silver lease rates collapse, indicating ample physical supply',
        'Silver mining major reports large production beat vs guidance',
        'Hedge funds increase net-short silver position to extreme level',
        'Silver demand from photography sector nearly extinct',
        'Silver/gold ratio fails to confirm gold breakout, silver lags',
        'Recycling volumes increase, boosting secondary silver supply',
        'Weak consumer electronics sales reduce silver plating demand',
        'Silver fails to hold above 200-day moving average after test',
        'Options market heavily skewed toward silver puts',
        'COMEX silver deliverable stocks increase to 18-month high',
    ],

    // ─────────────────────────────────────────────
    //  BONDS  — BULLISH (YIELDS DOWN / PRICES UP)
    // ─────────────────────────────────────────────
    BULLISH_BONDS: [
        'Fed signals imminent rate cut cycle, Treasuries surge',
        'Recession fears drive flight to safety into US bonds',
        'CPI cools sharply, removing inflation premium from bonds',
        'Fed Chair confirms inflation war is largely won',
        'Unemployment spikes, bond market prices in emergency cuts',
        '10-year Treasury yield drops below 4% on soft data',
        'Risk-off episode drives bond rally as equities crash',
        'Deflation signals in Europe lead to aggressive bond buying',
        'Fed resumes quantitative easing, purchasing Treasuries directly',
        'Bank crisis triggers emergency Fed bond purchase program',
        'Geopolitical shock sends capital into safe-haven bonds',
        'PCE deflator falls to 2% for first time in three years',
        'Global growth scare boosts demand for high-quality duration',
        'Yield curve steepens as Fed cuts front-end rates aggressively',
        'Pension fund LDI rebalancing drives massive bond buying',
        'Bank of Japan buys record volume of US Treasuries',
        'Foreign central banks increase Treasury reserves allocation',
        'Credit crisis pushes institutional funds into government bonds',
        'Treasury auction demand overwhelms supply, yields fall sharply',
        'Fed minutes show unanimous support for rate cut at next meeting',
        'Long-duration Treasury ETFs see record inflows',
        'Real yields fall as breakeven inflation drops with CPI',
        'Wage growth slows, suggesting further disinflation ahead',
        'Soft landing gives way to hard landing narrative, bonds win',
        'Treasury futures show record speculative long positioning',
        'Options on Treasuries show extreme call demand at lower yields',
        'Bond volatility (MOVE index) drops as Fed credibility rises',
        'Corporate bond spreads tighten, but Treasuries still attract flows',
        'Emergency rate cut by Fed surprises markets, bonds spike',
        'Fiscal discipline pledge by Congress reduces bond supply fears',
    ],

    BEARISH_BONDS: [
        'Fed holds rates higher for longer, bond bears maintain control',
        'US deficit spending triggers bond vigilante sell-off',
        'Inflation re-accelerates, Treasuries lose safe-haven status',
        'Treasury auction fails to attract sufficient demand',
        '10-year yield breaks above 5%, multi-decade resistance level',
        'US credit downgrade triggers global bond sell-off',
        'Bank of Japan ends yield curve control, global bonds reprice',
        'Quantitative tightening accelerates, removing bond market support',
        'Supply surge of new Treasury issuance overwhelms buyers',
        'Real yields turn deeply positive, bonds offer poor risk/reward',
        'TIPS market prices in persistent above-target inflation',
        'Long-duration bonds suffer worst quarterly loss in decades',
        'Traders dump Treasuries as fiscal outlook deteriorates',
        'Fed balance sheet reduction pace doubles, pressuring bonds',
        'Foreign official selling of US Treasuries reaches record pace',
        'China liquidates $50B in Treasuries to defend yuan',
        'Japan pension fund announces shift out of foreign bonds',
        'Term premium rises as bond investors demand higher compensation',
        'Consumer inflation expectations de-anchor from 2% target',
        'Stagflation scenario makes bonds and equities both unattractive',
        'US fiscal deficit projected to exceed 8% of GDP',
        'Interest expense on US debt surpasses defense budget',
        'Treasury issuance front-loaded into long-end, yield curve steepens',
        'Rising commodity prices reignite inflation fears for bond markets',
        'MOVE index spikes as bond volatility returns with vengeance',
        'Death spiral concerns emerge around debt sustainability trajectory',
        'Credit rating agency places US on negative outlook',
        'Bond short sellers expand positions as yields resume climb',
        '30-year Treasury yield tests 5.5%, longest duration hit hardest',
        'Inflation breakeven rates rise to 3.5%, above Fed comfort zone',
    ],
};
