import type { MarketPair } from 'src/prices-api/prices.api.types';

export const BULLISH_NEWS_KEYWORDS = [
  'rally',
  'surge',
  'soar',
  'jump',
  'gain',
  'rise',
  'climb',
  'bull',
  'bullish',
  'record high',
  'all-time high',
  'breakout',
  'recovery',
  'optimism',
  'upbeat',
  'dovish',
  'rate cut',
  'stimulus',
  'easing',
  'demand',
  'safe haven',
  'inflation fears',
  'hausse',
  'haussier',
  'montée',
  'rebond',
  'croissance',
  'achat',
  'growth',
  'positive',
  'strong',
  'outperform',
  'upgrade',
  'buy signal',
  'gold demand',
  'bitcoin adoption',
  'institutional buying',
  'etf inflow',
  'geopolitical tension',
  'war',
  'conflict',
  'sanctions',
  'uncertainty',
  'dollar weakness',
  'fed pause',
  'quantitative easing',
];

export const BEARISH_NEWS_KEYWORDS = [
  'crash',
  'plunge',
  'tumble',
  'drop',
  'fall',
  'decline',
  'bear',
  'bearish',
  'sell-off',
  'selloff',
  'correction',
  'collapse',
  'downturn',
  'pessimism',
  'hawkish',
  'rate hike',
  'tightening',
  'tapering',
  'recession',
  'baisse',
  'baissier',
  'chute',
  'effondrement',
  'vente',
  'negative',
  'weak',
  'underperform',
  'downgrade',
  'sell signal',
  'outflow',
  'liquidation',
  'ban',
  'regulation crackdown',
  'dollar strength',
  'fed hike',
  'quantitative tightening',
  'profit taking',
  'overbought',
  'bubble',
];

export const IMPACT_NEWS_KEYWORDS = [
  'fed',
  'federal reserve',
  'ecb',
  'bce',
  'central bank',
  'interest rate',
  'inflation',
  'cpi',
  'ppi',
  'gdp',
  'employment',
  'unemployment',
  'nfp',
  'non-farm',
  'fomc',
  'powell',
  'lagarde',
  'yellen',
  'war',
  'conflict',
  'sanctions',
  'trade war',
  'tariff',
  'opec',
  'oil',
  'energy crisis',
  'supply chain',
  'etf',
  'halving',
  'mining',
  'defi',
  'regulation',
  'breaking',
  'urgent',
  'flash crash',
  'black swan',
];

export const BULLISH_NEWS_SET = new Set(BULLISH_NEWS_KEYWORDS);
export const BEARISH_NEWS_SET = new Set(BEARISH_NEWS_KEYWORDS);
export const IMPACT_NEWS_SET = new Set(IMPACT_NEWS_KEYWORDS);

export const RSS_FEEDS: Record<MarketPair | 'GLOBAL', string[]> = {
  'XAU/USD': [
    'https://feeds.reuters.com/reuters/businessNews',
    'https://www.investing.com/rss/news_285.rss', // Gold news
  ],
  'BTC/USD': [
    'https://feeds.reuters.com/reuters/businessNews',
    'https://cointelegraph.com/rss',
  ],
  'ETH/USD': [
    'https://feeds.reuters.com/reuters/businessNews',
    'https://cointelegraph.com/rss',
  ],
  GLOBAL: [
    'https://feeds.reuters.com/reuters/businessNews',
    'https://cointelegraph.com/rss',
    'https://www.investing.com/rss/news.rss',
  ],
};

export function getFeedsForSymbol(symbol: MarketPair | string) {
  return (RSS_FEEDS as Record<string, string[]>)[symbol] || RSS_FEEDS.GLOBAL;
}
